.\" man page create by R# package system.
.TH OLLAMA 1 2000-1月 "setup_global_hook" "setup_global_hook"
.SH NAME
setup_global_hook \- hooks of the global LLMs api
.SH SYNOPSIS
\fIsetup_global_hook(\fBollama\fR as <generic> Ollama);\fR
.SH DESCRIPTION
.PP
hooks of the global LLMs api
.PP
.SH OPTIONS
.PP
\fBollama\fB \fR\- -. 
.PP
.SH SEE ALSO
ollama
.SH FILES
.PP
Agent.dll
.PP
