.\" man page create by R# package system.
.TH OLLAMA 1 2000-Jan "system_message" "system_message"
.SH NAME
system_message \- set or get the system message for the ollama client
.SH SYNOPSIS
\fIsystem_message(\fBmodel\fR as <generic> Ollama, 
\fBmsg\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set or get the system message for the ollama client
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBmsg\fB \fR\- -. 
.PP
.SH SEE ALSO
ollama
.SH FILES
.PP
Agent.dll
.PP
